# Generated by Django 2.1.12 on 2022-11-04 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'orders', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='ordersgoods',
            options={'verbose_name': 'ordersGoods', 'verbose_name_plural': 'ordersGoods'},
        ),
        migrations.AlterModelTable(
            name='orders',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='ordersgoods',
            table='ordersGoods',
        ),
    ]
