# Generated by Django 2.1.12 on 2022-11-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20221104_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='adress',
            field=models.CharField(default='shijiazhuang', max_length=200),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(default='11111111111', max_length=20),
        ),
        migrations.AddField(
            model_name='orders',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordersgoods',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
