# Generated by Django 2.1.12 on 2022-11-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20221107_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='value',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
    ]
