# Generated by Django 2.1.12 on 2022-11-11 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20221107_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_orders', to='users.Users'),
        ),
        migrations.AlterField(
            model_name='ordersgoods',
            name='good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='good_ordersGoods', to='goods.Goods'),
        ),
    ]
