# Generated by Django 2.1.12 on 2022-11-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
