# Generated by Django 2.1.12 on 2022-11-04 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartsgoods',
            options={'verbose_name': 'cartsGoods', 'verbose_name_plural': 'cartsGoods'},
        ),
        migrations.AlterModelTable(
            name='cartsgoods',
            table='cartsGoods',
        ),
    ]
